In [7]:
import torch
from models.localization_net import LocalizationNet


In [8]:
identity_affine_localization = LocalizationNet(
    in_channels=1,
    kernel_size=5,
    localization_channels=32,
    initialization_mode="identity",
    transformation_mode="affine",
    global_pooling="max"
)

input_fmap = torch.rand((1, 1, 28, 28))

with torch.no_grad():
  print(torch.round(identity_affine_localization(input_fmap)))


tensor([[[1., 0., 0.],
         [0., 1., 0.]]])


In [9]:
identity_rotation_localization = LocalizationNet(
    in_channels=1,
    kernel_size=5,
    localization_channels=32,
    initialization_mode="identity",
    transformation_mode="rotation",
    global_pooling="max"
)

input_fmap = torch.rand((1, 1, 28, 28))

with torch.no_grad():
  print(torch.round(identity_rotation_localization(input_fmap)))


tensor([[[1., -0., 0.],
         [0., 1., 0.]]])


In [10]:
random_affine_localization = LocalizationNet(
    in_channels=1,
    kernel_size=5,
    localization_channels=32,
    initialization_mode="random",
    transformation_mode="affine",
    global_pooling="max"
)

input_fmap = torch.rand((1, 1, 28, 28))

with torch.no_grad():
  print(random_affine_localization(input_fmap))


tensor([[[-0.0840, -0.0456,  0.0997],
         [ 0.8037, -0.4590,  0.8300]]])


In [11]:
random_rotation_localization = LocalizationNet(
    in_channels=1,
    kernel_size=5,
    localization_channels=32,
    initialization_mode="random",
    transformation_mode="rotation",
    global_pooling="max"
)

input_fmap = torch.rand((1, 1, 28, 28))

with torch.no_grad():
  print(random_rotation_localization(input_fmap))


tensor([[[-0.8321,  0.5546, -0.0000],
         [-0.5546, -0.8321, -0.0000]]])
